# Generated by Django 6.0.5 on 2026-05-26 06:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmissionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(choices=[('SCOPE_1', 'Scope 1 - Direct Emissions'), ('SCOPE_2', 'Scope 2 - Purchased Electricity'), ('SCOPE_3', 'Scope 3 - Value Chain')], max_length=10)),
                ('category', models.CharField(choices=[('STATIONARY_COMBUSTION', 'Stationary Combustion (boilers, generators)'), ('MOBILE_COMBUSTION', 'Mobile Combustion (company vehicles)'), ('PURCHASED_ELECTRICITY', 'Purchased Electricity'), ('BUSINESS_TRAVEL_AIR', 'Business Travel - Air'), ('BUSINESS_TRAVEL_HOTEL', 'Business Travel - Hotel'), ('BUSINESS_TRAVEL_GROUND', 'Business Travel - Ground Transport'), ('PURCHASED_GOODS', 'Purchased Goods & Services')], max_length=50)),
                ('source_type', models.CharField(choices=[('SAP_FUEL', 'SAP - Fuel & Procurement'), ('UTILITY_ELECTRICITY', 'Utility Portal - Electricity'), ('TRAVEL_CORPORATE', 'Corporate Travel (Concur/Navan)')], max_length=30)),
                ('activity_description', models.CharField(help_text="Human-readable: 'Diesel - Plant PL01 Mumbai'", max_length=500)),
                ('activity_date', models.DateField(help_text='Date of activity (not billing date)')),
                ('location', models.CharField(blank=True, help_text='Plant, site, or city', max_length=255)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=15)),
                ('unit', models.CharField(choices=[('LITRE', 'Litres'), ('KG', 'Kilograms'), ('M3', 'Cubic Metres'), ('KWH', 'Kilowatt Hours'), ('MWH', 'Megawatt Hours'), ('KM', 'Kilometres'), ('NIGHT', 'Hotel Nights')], max_length=10)),
                ('quantity_original', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('unit_original', models.CharField(blank=True, help_text="Original unit from source, e.g. 'GAL', 'M3', 'KWH'", max_length=50)),
                ('emission_factor', models.DecimalField(decimal_places=6, help_text='kgCO2e per unit', max_digits=12)),
                ('emission_factor_source', models.CharField(default='DEFRA 2024', help_text='Which factor database we used', max_length=100)),
                ('co2e_kg', models.DecimalField(decimal_places=4, help_text='Total kgCO2e = quantity × emission_factor', max_digits=15)),
                ('review_status', models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('FLAGGED', 'Flagged for Review'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.TextField(blank=True, help_text='Analyst notes on this record')),
                ('is_suspicious', models.BooleanField(default=False)),
                ('suspicious_reason', models.TextField(blank=True)),
                ('is_locked', models.BooleanField(default=False, help_text='True once approved for audit — cannot be changed')),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('edited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edited_records', to=settings.AUTH_USER_MODEL)),
                ('locked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locked_records', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_records', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emission_records', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-activity_date', 'scope'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATED', 'Record Created'), ('EDITED', 'Record Edited'), ('APPROVED', 'Record Approved'), ('FLAGGED', 'Record Flagged'), ('REJECTED', 'Record Rejected'), ('LOCKED', 'Record Locked for Audit'), ('NOTE_ADDED', 'Note Added')], max_length=20)),
                ('changes', models.JSONField(default=dict, help_text="{'field': ['old_value', 'new_value']}")),
                ('note', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='emissions.emissionrecord')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='IngestionJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('SAP_FUEL', 'SAP - Fuel & Procurement'), ('UTILITY_ELECTRICITY', 'Utility Portal - Electricity'), ('TRAVEL_CORPORATE', 'Corporate Travel (Concur/Navan)')], max_length=30)),
                ('file_name', models.CharField(max_length=500)),
                ('file_path', models.CharField(blank=True, max_length=1000)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('DONE', 'Done'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('total_rows', models.IntegerField(default=0)),
                ('success_rows', models.IntegerField(default=0)),
                ('failed_rows', models.IntegerField(default=0)),
                ('suspicious_rows', models.IntegerField(default=0)),
                ('error_summary', models.JSONField(blank=True, default=list)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingestion_jobs', to='tenants.tenant')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.AddField(
            model_name='emissionrecord',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emission_records', to='emissions.ingestionjob'),
        ),
        migrations.CreateModel(
            name='RawRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.IntegerField(help_text='Line number in the original file')),
                ('raw_data', models.JSONField(help_text='Exact original row as received — never modified')),
                ('parse_status', models.CharField(choices=[('OK', 'Parsed Successfully'), ('FAILED', 'Parse Failed'), ('SUSPICIOUS', 'Suspicious Value')], default='OK', max_length=20)),
                ('parse_errors', models.JSONField(default=list, help_text='List of error messages if parsing had issues')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_records', to='emissions.ingestionjob')),
            ],
            options={
                'ordering': ['job', 'row_number'],
            },
        ),
        migrations.AddField(
            model_name='emissionrecord',
            name='raw_record',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emission_record', to='emissions.rawrecord'),
        ),
    ]
