# Generated by Django 6.0.5 on 2026-05-29 15:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('analyst', 'Analyst'), ('viewer', 'Viewer')], default='analyst', help_text="User's role within this tenant", max_length=20)),
                ('name', models.CharField(help_text="Full legal name, e.g. 'Tata Steel Ltd - India Operations'", max_length=255)),
                ('slug', models.SlugField(help_text="URL-safe identifier, e.g. 'tata-steel-india'")),
                ('industry', models.CharField(blank=True, help_text="e.g. 'Steel Manufacturing'", max_length=100)),
                ('country', models.CharField(default='India', max_length=100)),
                ('reporting_year', models.IntegerField(default=2024, help_text='The fiscal/calendar year being reported')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(help_text='User associated with this tenant', on_delete=django.db.models.deletion.CASCADE, related_name='tenants', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('user', 'slug')},
            },
        ),
    ]
